### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [senolatac/spring-boot-aws-heroku#1]
Hi,<br><br>url : https://github.com/senolatac/spring-boot-aws-heroku/blob/231d55169b39920367be619be25d98eccd319750/src/main/resources/application-prod.properties <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by senolatac** [comment]
Thank you. But no problem. It's just a test db. And fake credentials.
